---
title: "About"
about:
  template: solana
---

## EDUCATION

The Johns Hopkins University    
Sept. 2022 - Expected May 2024    
Major: Biostatistics (Master of Science)

University of California Berkeley, Berkeley, CA   
Aug. 2021 - Dec. 2021   
GLOBE Visiting Student Program, Bioengineering    

University of Chinese Academy of Sciences, Beijing, China   
Sept. 2018 - June 2022    
Major: Biological Science (Bachelor of Science)		 
Minor: Computer Science

## ACADEMIC EXPERIENCES

Undergraduate Student Researcher | PI: Yi Du (duyi@psych.ac.cn)     
Jan. 2020 - Aug. 2021   
Institution: Institue of Psychology, Chinese Academy of Sciences    
Research: Long term of musical training enhances the ability of empathy   

Undergraduate Student Researcher | PI: Zhuqing Zhang (zhuqingzhang@ucas.ac.cn)    
June 2020 - Aug. 2021   
Institution: University of Chinese Academy of Sciences, College of Life Sciences    
Research: LLPSDB v2.0, an updated database of proteins undergoing liquid-liquid phase separation (LLPS) in vitro    

Teaching Assistant | Professor: Yanli Wang (ylwang@ibp.ac.cn)   
Sept. 2020 - Jan.  2021   
Institution: University of Chinese Academy of Sciences, College of Life Sciences    
Course: Experiments of Biochemistry and Molecular Biology   

## EXTRACURRICULAR ACTIVITIES                                                                                                                        
UCAS Science and Technology Department, Member    
Sept. 2018 - Jan. 2019    

UCAS Basketball Club, Vice President    
July 2019 - Oct. 2019

Paleozoological Museum of China, Volunteer as a Museum Interpreter    
Oct. 2019 - Dec. 2019


